<?xml version="1.0" encoding="utf-8"?><Database Name="dbmusic" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Artists" Member="Artists">
    <Type Name="Artist">
      <Column Name="ArtistID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArtistName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PackageName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ImageURL" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="SampleURL" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>